set_known_position:
  name: "Set Known Position"
  description: "Define a posição conhecida para a cobertura (cover)."
  fields:
    position:
      name: "Posição"
      description: "Posição (0 a 100)."
      example: 50
      required: true
    confident:
      name: "Confiante"
      description: "Indica se a posição é confiável / confirmada."
      example: true
      required: false
    position_type:
      name: "Tipo de Posição"
      description: "Tipo de posição ('target' ou 'current')."
      example: "target"
      required: false

set_known_action:
  name: "Set Known Action"
  description: "Define a ação conhecida (open, close ou stop) para a cobertura."
  fields:
    action:
      name: "Ação"
      description: "Ação a definir ('open', 'close' ou 'stop')."
      example: "open"
      required: true
