set_known_position:
  name: Set known position
  description: Inform the integration about a known cover position without triggering any action.
  target:
    entity:
      domain: cover
  fields:
    position:
      name: Position
      description: Desired or current position of the cover (0–100).
      example: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    confident:
      name: Confident
      description: Whether this position is known with confidence (default: false). Affects whether the entity assumes or confirms its state.
      example: true
      default: false
      selector:
        boolean: {}
    position_type:
      name: Position type
      description: Whether the given position refers to the target or the current position. Defaults to "target".
      example: current
      default: target
      selector:
        select:
          options:
            - target
            - current

set_known_action:
  name: Set known action
  description: Notify Home Assistant of a known cover action (open, close, or stop) captured externally, without triggering commands.
  target:
    entity:
      domain: cover
  fields:
    action:
      name: Action
      description: Must be one of "open", "close", or "stop".
      example: open
      selector:
        select:
          options:
            - open
            - close
            - stop
