set_known_position:
  name: "Definir posição conhecida"
  description: "Define manualmente a posição conhecida de uma cobertura."
  target:
    entity:
      domain: cover
  fields:
    position:
      name: Posição
      description: Valor de 0 a 100 representando a posição atual ou destino.
      example: 50
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    confident:
      name: Confiante
      description: Indica se a posição é confirmada (verdadeira).
      default: false
      selector:
        boolean: {}
    position_type:
      name: Tipo de posição
      description: Pode ser "current" ou "target".
      default: "target"
      selector:
        select:
          options:
            - "current"
            - "target"

set_known_action:
  name: "Definir ação conhecida"
  description: "Define manualmente a ação atual da cobertura (abrir, fechar, parar)."
  target:
    entity:
      domain: cover
  fields:
    action:
      name: Ação
      description: A ação atual.
      required: true
      example: "open"
      selector:
        select:
          options:
            - "open"
            - "close"
            - "stop"
